# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool: gadgetron-gpu-nodes

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    nvidia-smi
    docker run hello-world
    docker images
  displayName: 'Run a multi-line script'
