# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
  AzureConnection: 'BiomedicalImaging-NonProd(87d8acb3-5176-4651-b457-6ab9cefd8e3d)'

trigger:
- master

pool: gadgetron-gpu-nodes

steps:
- task: AzureKeyVault@1
  inputs:
    azureSubscription: $(AzureConnection)
    keyVaultName: gadgetron-build-secrets

- script: |
    echo "Build.Repository.Uri: $(Build.Repository.Uri)"
    echo "system.pullRequest.pullRequestNumber: $(system.pullRequest.pullRequestNumber)"
    echo "build.BuildNumber: $(build.BuildNumber)"
    echo "Build.SourceBranch: $(Build.SourceBranch)"
    echo "Build.SourceBranchName: $(Build.SourceBranchName)"
    echo "Build.SourceVersion: $(Build.SourceVersion)"
    echo "System.PullRequest.IsFork: $(System.PullRequest.IsFork)"
    echo "System.PullRequest.SourceRepositoryURI: $(System.PullRequest.SourceRepositoryURI)"
    echo "System.PullRequest.TargetBranch: $(System.PullRequest.TargetBranch)"
    echo "System.PullRequest.PullRequestId: $(System.PullRequest.PullRequestId)"
    echo "gcr-user: $(gcr-user)"
    echo "gcr-pat: $(gcr-pat)"
    nvidia-smi
    docker run --gpus all hello-world
    docker images
  displayName: 'Run a multi-line script'

- script: |
    echo "$(gcr-pat)" | docker login ghcr.io -u $(gcr-user) --password-stdin
    docker pull hello-world
    IMAGE_NAME="ghcr.io/gadgetron/gadgetron/gadgetron-test-image:latest"
    docker tag hello-world $IMAGE_NAME
    docker push $IMAGE_NAME
